Traceback (most recent call last):
  File "morse.py", line 100, in <module>
    w_1.extend(WORD_REP.get_vector(word[0]))
  File "/home/johnlee/Research/morse/vectorize_word.py", line 26, in get_vector
    return self.model[word]
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 576, in __getitem__
    return self.word_vec(words)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 275, in word_vec
    raise KeyError("word '%s' not in vocabulary" % word)
KeyError: u"word 'jb\uae08\uc735\uadf8\ub8f9\uc740' not in vocabulary"


KeyError: u"word '\u03b4\uc790\ub3d9' not in vocabulary